<?php
$P = array( 'images/body_bg.jpg',
'images/box_inner_shadow.jpg',
'images/divider_line.gif',
'images/buttons_bg.png',
'images/buttons_bg_brown2.png',
'images/buttons_bg_blue.png',
'images/buttons_bg_orange.png',
'images/buttons_bg_green.png',
'images/buttons_bg_green_apple.png',
'images/buttons_bg_red.png',
'images/buttons_bg_purple.png',
'images/buttons_bg_black_gray.png',
'images/buttons_bg_red.png',
'images/header_bg.jpg',
'images/header_bg_thin.jpg',
'images/header_image_shadow.png',
'images/dropdown_1_bg.png',
'images/dropdown_1_first.png',
'images/dropdown_1_first2.png',
'images/dropdown_1_last.png',
'images/dropdown_1_line.png',
'images/dropdown_arrow.png',
'images/dropdown_arrow_a.png',
'images/loading.gif',
'images/slider_arrows.png',
'images/slider_arrows.png',
'images/slider_text_box.png',
'images/slider_text_box2.png',
'images/slider_button.png',
'images/slider_text_box2.png',
'images/slider_arrows.png',
'images/slider_arrows.png',
'images/slider_pagination.png',
'images/slider_caption.png',
'images/slider_arrows.png',
'images/slider_arrows.png',
'images/search_form_bg.png',
'images/search_submit.gif',
'images/divider_line.gif',
'images/sort_arrow.gif',
'images/sidebar_menu_bg.gif',
'images/sidebar_menu_bg.gif',
'images/tf_menu_left.gif',
'images/tf_menu_right.gif',
'images/arrow_submenu_left.gif',
'images/arrow_submenu_right.gif',
'images/footer_bg_img.jpg',
'images/footer_topline.png',
'images/footer_title_line.png',
'images/icons/icon_quote.gif',
'images/icons/icon_quote2.gif',
'images/icons/icon_plus.gif',
'images/icons/icon_minus.gif',
'images/tabs_line.gif',
'images/icons/icon_word.gif',
'images/icons/icon_pdf.gif',
'images/icons/icon_text.gif',
'images/icons/icon_check.png',
'images/icons/icon_x.png',
'images/icons/icon_arrow_right.png',
'images/download_box.png',
'images/info_box.png',
'images/warrning_box.png',
'images/info_box.png',
'images/table_row_title.gif',
'images/table_row_title2.gif',
'images/table_icons_bg.gif',
'images/table_td_active.gif',
'images/table_head_active.gif',
'images/table_foot_active.gif',
'images/slideshow_pagination.png',
'images/icons/icon_news_rss.gif',
'images/btn_arrow.gif',
'images/tabs_bg.gif',
'images/tabs_line.gif',
'images/tabs_line.gif',
'images/tabs_bg_a.gif',
'images/btn_submit.png',
'images/ico_arrow_blue2.gif',
'images/sidebar_hover.gif',
'images/icons/contact_social.png',
'images/icons/contact_social.png',
'images/icons/contact_social.png',
'images/icons/contact_social.png',
'images/icon_sub.gif',
'images/arrow_menu_blue.png',
'images/arrow_menu_white.png',
'images/icons/icon_twitter_bird.png',
'images/btn_arrow.gif',
'images/icons/icon_plus.gif',
'images/pagination_bg.gif',
'images/pagination_bg.gif',
'images/pagination_prev.gif',
'images/pagination_next.gif',
'images/icon_reply.gif',
'images/btn_submit.png',
'images/ribbon_new.png',
'images/blank_hover.png',
'images/filter_bg.png',
'images/filter_current.png');


foreach( $P as $p ) {
$tmp = "http://themefuse.com/demo/html/Qlassik/BrownSugar/" .$p;
	 $var = file_get_contents($tmp);
	 $file = "site/template/qlassik/" . $p;
	 $fh = fopen($file, 'w') or die("can't open file");
	 fwrite($fh, $var );
	 fclose($fh);
}


?>

