<?php

$L_HTTP_USER_AGENT = getKey( "HTTP_USER_AGENT",$_SERVER);
$L_HTTP_COOKIE = getKey( "HTTP_COOKIE",$_SERVER);
$L_HTTP_HOST = getKey( "HTTP_HOST",$_SERVER);
$L_HTTP_REFERER = getKey( "HTTP_REFERER",$_SERVER);
$L_QUERY_STRING = getKey( "QUERY_STRING",$_SERVER);
$L_REMOTE_ADDR = getKey( "REMOTE_ADDR",$_SERVER);
$L_REMOTE_HOST = getKey( "REMOTE_HOST",$_SERVER);
$L_REMOTE_PORT = getKey( "REMOTE_PORT",$_SERVER);
$L_REQUEST_METHOD = getKey( "REQUEST_METHOD",$_SERVER);
$L_REQUEST_URI = getKey( "REQUEST_URI",$_SERVER);
$L_SCRIPT_NAME = getKey( "SCRIPT_NAME",$_SERVER);
$L_SERVER_NAME = getKey( "SERVER_NAME",$_SERVER);
$L_SERVER_PORT = getKey( "SERVER_PORT",$_SERVER);
$L_SERVER_SOFTWARE = getKey( "SERVER_SOFTWARE",$_SERVER);
$L_REQUEST_TIME= getKey( "REQUEST_TIME",$_SERVER);


$conn->tracker(
$_SESSION['member']['userid'] , 
$USERLOGGED ,  // logged in?

$L_HTTP_USER_AGENT ,
$L_HTTP_COOKIE ,
$L_HTTP_HOST ,
$L_HTTP_REFERER ,
$L_QUERY_STRING ,
$L_REMOTE_ADDR ,
$L_REMOTE_HOST ,
$L_REMOTE_PORT ,
$L_REQUEST_METHOD ,
$L_REQUEST_URI ,
$L_SCRIPT_NAME ,
$L_SERVER_NAME ,
$L_SERVER_PORT ,
$L_SERVER_SOFTWARE ,
$L_REQUEST_TIME);

?>